# Configuration file
SMTP_server: smtp.org.com
SMTP_port: 25
SMTP_tls: 
SMTP_user: 
SMTP_password: 
Email_from: user@org.com
Email_subject: New Checkmarx Scan is done!
Email_body: "Scan results URL:"
SAST_url: Chckmarx_server_URL
SAST_username: admin   
SAST_password: 123456
SAST_proxy:



